### ISSUE TITLE
GreenGenes OTU table as output

### ISSUE THREAD

**Issue by TonyaWard** [knights-lab/SHOGUN#2]
It would be helpful to have shogun also output a GreenGenes OTU table that can be plugged into tools that require GG IDs, such as BugBase :).  Attached is the gg to img map.
[gg_13_5_img.txt](https://github.com/knights-lab/NINJA-Shogun/files/263707/gg_13_5_img.txt)

**Comment by bhillmann** [comment]
Deprecated functionality. I don't believe this is relevant anymore.
