### ISSUE TITLE
Error Running UTREE with SHOGUN-BUGBASE

### ISSUE THREAD

**Issue by cmstaley** [knights-lab/SHOGUN#3]
I'm trying to run shogun_bugbase with the command 

shogun_bugbase -i /panfs/roc/scratch/staleyc/byron/ssg/ -o /panfs/roc/scratch/staleyc/byron/ssg/shogun/ -u /home/sadowsky/staleyc/shogun_bugbase_db

Everything seems to have installed properly and is extracted. I think all of the paths are linked in the .bashrc. I have R ver 3.3.1 loaded and all of the packages (except grid) installed. I get the following error

Traceback (most recent call last):
  File "/home/sadowsky/staleyc/miniconda3/envs/shogun/bin/shogun_bugbase", line 11, in <module>
    load_entry_point('ninja-shogun==0.0.1.dev0', 'console_scripts', 'shogun_bugbase')()
  File "/home/sadowsky/staleyc/miniconda3/envs/shogun/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/sadowsky/staleyc/miniconda3/envs/shogun/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/sadowsky/staleyc/miniconda3/envs/shogun/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sadowsky/staleyc/miniconda3/envs/shogun/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/sadowsky/staleyc/miniconda3/envs/shogun/lib/python3.5/site-packages/ninja_shogun/scripts/shogun_bugbase.py", line 51, in shogun_bugbase
    with open(utree_tsv) as inf:
FileNotFoundError: [Errno 2] No such file or directory: '/panfs/roc/scratch/staleyc/byron/ssg/017.baseline.S12.utree.tsv'

I tried installing UTREE again using the compilation instructions with the shogun environment up and also copied the UTREE scripts into /miniconda3/envs/shogun/bin.

The only files in the input directory are .fna files and the log file from shi7en.

Any thoughts on how to fix this?

**Comment by bhillmann** [comment]
Can I get access to:

```
/panfs/roc/scratch/staleyc/byron/ssg/shogun
```

To see if anything is in there?

**Comment by cmstaley** [comment]
You should have access now, but I don't see anything there. The command failed pretty quickly.

**Comment by bhillmann** [comment]
I don't think UTree is working from those binaries.

Try running:

```
utree-search
```

@GabeAl Can you add you add 'static' compile to the makefile for UTree? The release binaries zip folder isn't working correctly because the binaries are a bit small.

**Comment by cmstaley** [comment]
UTree is not working:
utree-search: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by utree-search)

**Comment by GabeAl** [comment]
Got it. Yes, for some reason the binary wasn't static. I will upload the
static binaries within the hour.

Thanks for the report!

**Comment by cmstaley** [comment]
Thanks. I reinstalled UTree this morning and the command worked.

**Comment by bhillmann** [comment]
I am closing this issue. It sounds like everything worked.
